apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: metabase
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
data:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: "5432"
  MB_DB_USER: admin
  MB_DB_PASS: admin
  MB_DB_HOST: database.default.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
      - name: database
        image: postgres:13.1
        envFrom:
        - configMapRef:
            name: postgres-config
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    name: database
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metabase
  template:
    metadata:
      labels:
        name: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        envFrom:
        - configMapRef:
            name: metabase-config
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  selector:
    name: metabase
  ports:
  - port: 3000
    targetPort: 3000
